export enum RESPONSE_TYPE {
    SUMMARY = "SUMMARY",
    DETAILED = "DETAILED"
};

export enum EVENTS_NAMES {
    DELIVERY_STATUS_CHANGE = "DELIVERY_STATUS_CHANGE",
    TRXN_STATUS_CHANGE = "TRXN_STATUS_CHANGE"
}