export enum DELIVERY_STATUS {
    PACKED = "PACKED",
    SHIPPED = "SHIPPED",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED"
};

export enum PATMENT_MODE {
    ONLINE = "ONLINE",
    COD = "COD"
}